config/routes.rb
Rails.application.routes.draw do
  resources :comptes
  devise_for :users

  root 'comptes#index'

end

app/models/compte.rb
class Compte < ActiveRecord::Base
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
  before_action :authenticate_user!
  before_filter :configure_permitted_parameters, if: :devise_controller?
def configure_permitted_parameters
   devise_parameter_sanitizer.for(:sign_up) { |u| u.permit(:username, :email, :password, :phone, :subscribe, :gender, :adress, :citycode, :city, :password_confirmation) }
   devise_parameter_sanitizer.for(:account_update) { |u| u.permit(:username, :email, :password, :phone, :subscribe, :gender, :adress, :citycode, :city, :current_password, :password_confirmation) }
end
end

app/controllers/comptes_controller.rb
class ComptesController < ApplicationController
  before_action :set_compte, only: [:show, :edit, :update, :destroy]

  # GET /comptes
  # GET /comptes.json
  def index
    @comptes = Compte.all
    if current_user.sign_in_count==1
      UserMailer.welcome_email(current_user).deliver_now
    end
  end

  # GET /comptes/1
  # GET /comptes/1.json
  def show
  end

  # GET /comptes/new
  def new
    @compte = Compte.new
  end

  # GET /comptes/1/edit
  def edit
  end

  # POST /comptes
  # POST /comptes.json
  def create
    @compte = Compte.new(compte_params)

    respond_to do |format|
      if @compte.save
        format.html { redirect_to @compte, notice: 'Compte was successfully created.' }
        format.json { render :show, status: :created, location: @compte }
      else
        format.html { render :new }
        format.json { render json: @compte.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /comptes/1
  # PATCH/PUT /comptes/1.json
  def update
    respond_to do |format|
      if @compte.update(compte_params)
        format.html { redirect_to @compte, notice: 'Compte was successfully updated.' }
        format.json { render :show, status: :ok, location: @compte }
      else
        format.html { render :edit }
        format.json { render json: @compte.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /comptes/1
  # DELETE /comptes/1.json
  def destroy
    @compte.destroy
    respond_to do |format|
      format.html { redirect_to comptes_url, notice: 'Compte was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_compte
      @compte = Compte.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def compte_params
      params.require(:compte).permit(:name)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
  def bootstrap_class_for flash_type
    { success: "alert-success", error: "alert-danger", alert: "alert-warning", notice: "alert-info" }[flash_type.to_sym] || flash_type.to_s
  end

  def flash_messages(opts = {})
    flash.each do |msg_type, message|
      concat(content_tag(:div, message, class: "alert #{bootstrap_class_for(msg_type)} alert-dismissible", role: 'alert') do
               concat(content_tag(:button, class: 'close', data: { dismiss: 'alert' }) do
                        concat content_tag(:span, '&times;'.html_safe, 'aria-hidden' => true)
                        concat content_tag(:span, 'Close', class: 'sr-only')
               end)
               concat message
      end)
    end
    nil
  end
end

app/helpers/comptes_helper.rb
module ComptesHelper
end

app/views/comptes/_form.html.erb
<%= form_for(@compte) do |f| %>
  <% if @compte.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@compte.errors.count, "error") %> prohibited this compte from being saved:</h2>

      <ul>
      <% @compte.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/comptes/edit.html.erb
<h1>Editing Compte</h1>

<%= render 'form' %>

<%= link_to 'Show', @compte %> |
<%= link_to 'Back', comptes_path %>

app/views/comptes/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Comptes</h1>

<table id="table1">
  <thead>
    <tr>
      <th>Name</th>
      <th></th>
      <th></th>
      <th></th>
    </tr>
  </thead>

  <tbody>
    <% @comptes.each do |compte| %>
      <tr>
        <td><%= compte.name %></td>
        <td><%= link_to 'Show', compte %></td>
        <td><%= link_to 'Edit', edit_compte_path(compte) %></td>
        <td><%= link_to 'Destroy', compte, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Compte', new_compte_path %>

app/views/comptes/new.html.erb
<h1>New Compte</h1>

<%= render 'form' %>

<%= link_to 'Back', comptes_path %>

app/views/comptes/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @compte.name %>
</p>

<%= link_to 'Edit', edit_compte_path(@compte) %> |
<%= link_to 'Back', comptes_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>MailerRb</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>
  <% if user_signed_in? %>
<%= current_user.email %>
<%= link_to 'Edit profile', edit_user_registration_path %>
<%= link_to "Se deconnecter", destroy_user_session_path, method: :delete %>
<% else %>
<%= link_to "S'inscrire", new_user_registration_path %>
<%= link_to "Se connecter", new_user_session_path %>
<% end %>
<div class="message"><%= flash_messages %></div>
<%= yield %>

</body>
</html>